### ISSUE TITLE
Running migrations fails; iCal link 404s; images in grid stretched

### ISSUE THREAD

**Issue by justinlaselva** [julianpoy/RecipeSage-selfhost#31]
Howdy! I'm still loving RecipeSage and thanks, again, for developing it and making a self-hosted version. I finally got around to updating from 2.8.0 to 2.9.0 and I've noticed three issues since the upgrade:

1. Running the migrations fails for me. When I run `docker-compose exec api /app/migrate`, I get the following error:

```
pkg/prelude/bootstrap.js:1930
      return wrapper.apply(this.exports, args);
                     ^

TypeError: object is not a constructor
    at Object.<anonymous> (/snapshot/app/Backend/src/migrate.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47
ERROR: 1
```

Things seem to work fine without this completing successfully but, since the documentation says to run migrations after each upgrade, this seems like a problem.

2. The link provided to share my meal plans via .ics file 404s. I can reach the `/api` endpoint and receive the welcome message, but attempting to load the actual .ics file fails with this error:

```
Not Found
404

Error: Not Found
    at /snapshot/app/Backend/src/app.js
    at Layer.handle [as handle_request] (/snapshot/app/Backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/snapshot/app/Backend/node_modules/express/lib/router/index.js:328:13)
    at /snapshot/app/Backend/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/snapshot/app/Backend/node_modules/express/lib/router/index.js:346:12)
    at next (/snapshot/app/Backend/node_modules/express/lib/router/index.js:280:10)
    at /snapshot/app/Backend/node_modules/express/lib/router/index.js:646:15
    at next (/snapshot/app/Backend/node_modules/express/lib/router/index.js:265:14)
    at Function.handle (/snapshot/app/Backend/node_modules/express/lib/router/index.js:175:3)
    at router (/snapshot/app/Backend/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/snapshot/app/Backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/snapshot/app/Backend/node_modules/express/lib/router/index.js:328:13)
    at /snapshot/app/Backend/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/snapshot/app/Backend/node_modules/express/lib/router/index.js:346:12)
    at next (/snapshot/app/Backend/node_modules/express/lib/router/index.js:280:10)
    at cookieParser (/snapshot/app/Backend/node_modules/cookie-parser/index.js:46:14)
```

Related to this, the pop-up box that comes up when you click Share, that shows the URL for the .ics file, doesn't include the hostname of the system on which RecipeSage is running, so you can't actually just copy and paste that not-quite-address into your calendaring program. I'm not sure what facilities exist to glean the hostname of the host system in order to prefix the .ics file address (perhaps there isn't one?), but if there is, it would be more friendly to the user to include it.

3. Finally, one minor nitpick… I'm fairly certain v2.8.0 was scaling down non-square images to fit the grid on the My Recipes page; now, it looks like v2.9.0 is maybe altering the aspect ratio of those images to fit the square grid. I have a rectangular photo of a tasty baked ham for my ham recipe, and before it looked great! Now, it looks squished lengthwise to fit in that square container. Not a big deal, just thought I'd mention that the previous scaling behavior seemed to work better for non-square images. Either that, or my memory is wrong, and the image looked squished all along!

Again, thanks!

**Comment by julianpoy** [comment]
Hi @justinlaselva thanks for the bug report! I'll definitely look into this, but just a heads up that v2.9.0 is still in beta and isn't really usable in selfhost quite yet.

Nevertheless, the list of issues above is super helpful for prepping for the full stable release!

**Comment by justinlaselva** [comment]
Aha! Thanks, good to know. I had updated my docker-compose file to use the api-latest and static-latest tags, but I've reverted back to the 2.8.1 used in your self-host repo's docker-compose file, and everything seems to be back how it was.

**Comment by julianpoy** [comment]
Having trouble replicating #3. Appears to work correctly for me on the latest beta.

**Comment by julianpoy** [comment]
v2.9.0 stable has been released. All of the issues above have been fixed, aside from  number 3 which I cannot replicate.
