### ISSUE TITLE
v2.11.0-beta8/9 fails to add an image by URL - 400 response from backend

### ISSUE THREAD

**Issue by ahhmino** [julianpoy/RecipeSage-selfhost#43]
**Describe the bug**
Tested on 2.11.0-beta8 and beta9. While editing a recipe and uploading an image using an image url, the frontend sends a POST json payload with the field `imageUrl` to the api endpoint `/api/images`. The backend still handles only multipart file object payload for this endpoint - expecting a field named `image` (see logs below), so it throws a 400 bad request and fails to upload image using the url (at least I didn't find an implementation in the backend src for handling imageUrl, please correct me if I'm wrong)

Another note, this bug was only seen in the self hosted version, using docker. The hosted version of RecipeSage doesn't have this issue when I tested on a free account.

I really like RecipeSage, is there a docker image version I can revert to in the meantime? I tested a few other beta versions, all had the same issue - had some trouble trying 2.10.0 given the switch from monio to filesystem change that happened.

This might just be a bug with the self hosted version if the hosted service works fine, but if the functionality is missing I'm also happy to open a PR!

**What page/area is the bug in?**
Recipe editor, image url dialog box

**To Reproduce**
1. Run the docker-compose.yaml from the self hosted repo using version 2.11.0-beta8 (or 9) for the frontend and backend.
2. Run the ./migrate.sh and ./activate.sh scripts
3. Create account/login, click on fab add recipe button in bottom right. Save recipe after filling out fields.
4. Click on edit recipe
5. Click on options button in the top right
6. Select "Add image by url"
7. Enter an image link in the dialogue box, then click Confirm
8. Verify error toast is shown, and 400 request is received in browser developer tools.

**Expected behavior**
Image should be downloaded and added to recipe using the provided url

**Screenshots**
Screenshots showing 400 response in browser developer tools + `imageUrl` being posted in the request payload

![400 response from POST](https://user-images.githubusercontent.com/38871201/231344869-8b8277af-10ca-46e4-a1a8-9bdbbb3ff1eb.png)

![Request body with `imageUrl`](https://user-images.githubusercontent.com/38871201/231344939-d542865c-0c07-4a6c-80bf-e7e3b6a50e4c.png)

Logs from backend showing bad request:
```
POST /images?token=*** 400 44.852 ms - 1060
Error: Must specify multipart field "image"
    at constructError (/app/packages/backend/src/utils/errors.js:2:13)
    at BadRequest (/app/packages/backend/src/utils/errors.js:8:33)
    at <anonymous> (/app/packages/backend/src/routes/images.js:28:13)
    at <anonymous> (/app/packages/backend/src/utils/wrapRequestWithErrorHandler.js:4:13)
    at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at multerMiddleware (/app/node_modules/multer/lib/make-middleware.js:13:41)
    at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at <anonymous> (/app/packages/backend/src/services/middleware.js:18:7)
```
 

**Desktop (please complete the following information):**
 - OS: Docker (hosted on ubuntu server)
 - Browser: Firefox, Chrome

**Comment by ahhmino** [comment]
Ah I was still looking through the codebase, I see `imageUrl` was previously used as part of cloud storage integration and removed as part of the filesystem direct storage change? https://github.com/julianpoy/RecipeSage/pull/999/files#diff-7823b77281f3f8218780fd44a711de1a63f0471bc3de002810011891e8a8738e

That makes sense if so. I'm not sure how the self-hosted implementation differs from the hosted version, but in any case I'm still open to creating a PR for adding imageUrl support by downloading the image as in the previous implementation - just with the change of saving to disk for self hosted
