### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by sandy9999** [julianpoy/RecipeSage-selfhost#46]
**Following are my VM specs:**
OS: Linux (Ubuntu 22.04)
Size: Standard D2s V3 (2 vcpus, 8 GiB memory) on Azure

Installed Docker by following: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04

Installed Docker Compose by following: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04

I forked the repository today and ran the following:

git clone https://github.com/sandy9999/RecipeSage-selfhost
cd RecipeSage-selfhost
docker compose up

<img width="565" alt="image" src="https://github.com/julianpoy/RecipeSage-selfhost/assets/17477947/4296347c-71e3-4968-9c7d-33feee9d23bc">

Observed the above. When I try to create an account on the self hosted version, I get "An unexpected error occurred. Please try again. If the problem continues to occur, please contact me."

Any ideas on how I can debug this?

**Comment by julianpoy** [comment]
Hey there! Assuming you followed all of the steps in the [setup section](https://github.com/julianpoy/RecipeSage-selfhost#setup) including the migration, could you post the logs just from the API container (docker-compose logs -f api)?

**Comment by julianpoy** [comment]
Closing since no response, but feel free to re-open.

**Comment by sandy9999** [comment]
Hi @julianpoy  Apologies for the late reponse. Here are the logs that you asked for,

```
recipesage-selfhost-api-1  | Error while initializing firebase for notifications
recipesage-selfhost-api-1  | /app/node_modules/@elastic/transport/lib/Transport.js:528
recipesage-selfhost-api-1  |                             : new errors_1.ConnectionError(error.message, result);
recipesage-selfhost-api-1  |                               ^
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | ConnectionError: connect ECONNREFUSED 172.19.0.7:9200
recipesage-selfhost-api-1  |     at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)
recipesage-selfhost-api-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
recipesage-selfhost-api-1  |     at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)
recipesage-selfhost-api-1  |     at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {
recipesage-selfhost-api-1  |   meta: {
recipesage-selfhost-api-1  |     body: undefined,
recipesage-selfhost-api-1  |     statusCode: 0,
recipesage-selfhost-api-1  |     headers: {},
recipesage-selfhost-api-1  |     meta: {
recipesage-selfhost-api-1  |       context: null,
recipesage-selfhost-api-1  |       request: {
recipesage-selfhost-api-1  |         params: {
recipesage-selfhost-api-1  |           method: 'HEAD',
recipesage-selfhost-api-1  |           path: '/',
recipesage-selfhost-api-1  |           querystring: '',
recipesage-selfhost-api-1  |           headers: {
recipesage-selfhost-api-1  |             'user-agent': 'elastic-transport-js/8.3.1 (linux 5.15.0-1037-azure-x64; Node.js v18.16.0)',
recipesage-selfhost-api-1  |             'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',
recipesage-selfhost-api-1  |             accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         options: {},
recipesage-selfhost-api-1  |         id: 1
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       name: 'elasticsearch-js',
recipesage-selfhost-api-1  |       connection: Connection {
recipesage-selfhost-api-1  |         url: <ref *1> URL {
recipesage-selfhost-api-1  |           [Symbol(context)]: URLContext {
recipesage-selfhost-api-1  |             href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',
recipesage-selfhost-api-1  |             origin: 'http://elasticsearch:9200',
recipesage-selfhost-api-1  |             protocol: 'http:',
recipesage-selfhost-api-1  |             hostname: 'elasticsearch',
recipesage-selfhost-api-1  |             pathname: '/',
recipesage-selfhost-api-1  |             search: '',
recipesage-selfhost-api-1  |             username: 'elastic',
recipesage-selfhost-api-1  |             password: 'recipesage_selfhost',
recipesage-selfhost-api-1  |             port: '9200',
recipesage-selfhost-api-1  |             hash: ''
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(query)]: URLSearchParams {
recipesage-selfhost-api-1  |             [Symbol(query)]: [],
recipesage-selfhost-api-1  |             [Symbol(context)]: [Circular *1]
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         tls: null,
recipesage-selfhost-api-1  |         id: 'http://elasticsearch:9200/',
recipesage-selfhost-api-1  |         timeout: 30000,
recipesage-selfhost-api-1  |         headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },
recipesage-selfhost-api-1  |         deadCount: 0,
recipesage-selfhost-api-1  |         resurrectTimeout: 0,
recipesage-selfhost-api-1  |         _openRequests: 0,
recipesage-selfhost-api-1  |         weight: 1000,
recipesage-selfhost-api-1  |         pool: <ref *2> Pool {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false,
recipesage-selfhost-api-1  |           [Symbol(destroyed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onDestroyed)]: [],
recipesage-selfhost-api-1  |           [Symbol(closed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onClosed)]: [],
recipesage-selfhost-api-1  |           [Symbol(queue)]: FixedQueue {
recipesage-selfhost-api-1  |             tail: [FixedCircularBuffer],
recipesage-selfhost-api-1  |             head: [FixedCircularBuffer]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(clients)]: [ [Client], [Client] ],
recipesage-selfhost-api-1  |           [Symbol(queued)]: 0,
recipesage-selfhost-api-1  |           [Symbol(onDrain)]: [Function: onDrain],
recipesage-selfhost-api-1  |           [Symbol(onConnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onDisconnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onConnectionError)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },
recipesage-selfhost-api-1  |           [Symbol(dispatch interceptors)]: [],
recipesage-selfhost-api-1  |           [Symbol(connections)]: 256,
recipesage-selfhost-api-1  |           [Symbol(url)]: URL {
recipesage-selfhost-api-1  |             [Symbol(context)]: [URLContext],
recipesage-selfhost-api-1  |             [Symbol(query)]: [URLSearchParams]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(options)]: {
recipesage-selfhost-api-1  |             keepAliveTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveMaxTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveTimeoutThreshold: 1000,
recipesage-selfhost-api-1  |             pipelining: 1,
recipesage-selfhost-api-1  |             maxHeaderSize: 16384,
recipesage-selfhost-api-1  |             headersTimeout: 30000,
recipesage-selfhost-api-1  |             bodyTimeout: 30000,
recipesage-selfhost-api-1  |             connect: [Function: connect],
recipesage-selfhost-api-1  |             interceptors: undefined
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(factory)]: [Function: defaultFactory],
recipesage-selfhost-api-1  |           [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],
recipesage-selfhost-api-1  |           [Symbol(needDrain)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(status)]: 'alive',
recipesage-selfhost-api-1  |         [Symbol(ca fingerprint)]: null,
recipesage-selfhost-api-1  |         [Symbol(diagnostics)]: Diagnostic {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(event emitter)]: EventEmitter {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         }
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       attempts: 3,
recipesage-selfhost-api-1  |       aborted: false
recipesage-selfhost-api-1  |     },
recipesage-selfhost-api-1  |     warnings: [Getter]
recipesage-selfhost-api-1  |   }
recipesage-selfhost-api-1  | }
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | Node.js v18.16.0
recipesage-selfhost-api-1  | Error while initializing firebase for notifications
recipesage-selfhost-api-1  | /app/node_modules/@elastic/transport/lib/Transport.js:528
recipesage-selfhost-api-1  |                             : new errors_1.ConnectionError(error.message, result);
recipesage-selfhost-api-1  |                               ^
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | ConnectionError: connect ECONNREFUSED 172.19.0.7:9200
recipesage-selfhost-api-1  |     at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)
recipesage-selfhost-api-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
recipesage-selfhost-api-1  |     at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)
recipesage-selfhost-api-1  |     at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {
recipesage-selfhost-api-1  |   meta: {
recipesage-selfhost-api-1  |     body: undefined,
recipesage-selfhost-api-1  |     statusCode: 0,
recipesage-selfhost-api-1  |     headers: {},
recipesage-selfhost-api-1  |     meta: {
recipesage-selfhost-api-1  |       context: null,
recipesage-selfhost-api-1  |       request: {
recipesage-selfhost-api-1  |         params: {
recipesage-selfhost-api-1  |           method: 'HEAD',
recipesage-selfhost-api-1  |           path: '/',
recipesage-selfhost-api-1  |           querystring: '',
recipesage-selfhost-api-1  |           headers: {
recipesage-selfhost-api-1  |             'user-agent': 'elastic-transport-js/8.3.1 (linux 5.15.0-1037-azure-x64; Node.js v18.16.0)',
recipesage-selfhost-api-1  |             'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',
recipesage-selfhost-api-1  |             accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         options: {},
recipesage-selfhost-api-1  |         id: 1
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       name: 'elasticsearch-js',
recipesage-selfhost-api-1  |       connection: Connection {
recipesage-selfhost-api-1  |         url: <ref *1> URL {
recipesage-selfhost-api-1  |           [Symbol(context)]: URLContext {
recipesage-selfhost-api-1  |             href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',
recipesage-selfhost-api-1  |             origin: 'http://elasticsearch:9200',
recipesage-selfhost-api-1  |             protocol: 'http:',
recipesage-selfhost-api-1  |             hostname: 'elasticsearch',
recipesage-selfhost-api-1  |             pathname: '/',
recipesage-selfhost-api-1  |             search: '',
recipesage-selfhost-api-1  |             username: 'elastic',
recipesage-selfhost-api-1  |             password: 'recipesage_selfhost',
recipesage-selfhost-api-1  |             port: '9200',
recipesage-selfhost-api-1  |             hash: ''
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(query)]: URLSearchParams {
recipesage-selfhost-api-1  |             [Symbol(query)]: [],
recipesage-selfhost-api-1  |             [Symbol(context)]: [Circular *1]
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         tls: null,
recipesage-selfhost-api-1  |         id: 'http://elasticsearch:9200/',
recipesage-selfhost-api-1  |         timeout: 30000,
recipesage-selfhost-api-1  |         headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },
recipesage-selfhost-api-1  |         deadCount: 0,
recipesage-selfhost-api-1  |         resurrectTimeout: 0,
recipesage-selfhost-api-1  |         _openRequests: 0,
recipesage-selfhost-api-1  |         weight: 1000,
recipesage-selfhost-api-1  |         pool: <ref *2> Pool {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false,
recipesage-selfhost-api-1  |           [Symbol(destroyed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onDestroyed)]: [],
recipesage-selfhost-api-1  |           [Symbol(closed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onClosed)]: [],
recipesage-selfhost-api-1  |           [Symbol(queue)]: FixedQueue {
recipesage-selfhost-api-1  |             tail: [FixedCircularBuffer],
recipesage-selfhost-api-1  |             head: [FixedCircularBuffer]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(clients)]: [ [Client], [Client] ],
recipesage-selfhost-api-1  |           [Symbol(queued)]: 0,
recipesage-selfhost-api-1  |           [Symbol(onDrain)]: [Function: onDrain],
recipesage-selfhost-api-1  |           [Symbol(onConnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onDisconnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onConnectionError)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },
recipesage-selfhost-api-1  |           [Symbol(dispatch interceptors)]: [],
recipesage-selfhost-api-1  |           [Symbol(connections)]: 256,
recipesage-selfhost-api-1  |           [Symbol(url)]: URL {
recipesage-selfhost-api-1  |             [Symbol(context)]: [URLContext],
recipesage-selfhost-api-1  |             [Symbol(query)]: [URLSearchParams]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(options)]: {
recipesage-selfhost-api-1  |             keepAliveTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveMaxTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveTimeoutThreshold: 1000,
recipesage-selfhost-api-1  |             pipelining: 1,
recipesage-selfhost-api-1  |             maxHeaderSize: 16384,
recipesage-selfhost-api-1  |             headersTimeout: 30000,
recipesage-selfhost-api-1  |             bodyTimeout: 30000,
recipesage-selfhost-api-1  |             connect: [Function: connect],
recipesage-selfhost-api-1  |             interceptors: undefined
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(factory)]: [Function: defaultFactory],
recipesage-selfhost-api-1  |           [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],
recipesage-selfhost-api-1  |           [Symbol(needDrain)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(status)]: 'alive',
recipesage-selfhost-api-1  |         [Symbol(ca fingerprint)]: null,
recipesage-selfhost-api-1  |         [Symbol(diagnostics)]: Diagnostic {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(event emitter)]: EventEmitter {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         }
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       attempts: 3,
recipesage-selfhost-api-1  |       aborted: false
recipesage-selfhost-api-1  |     },
recipesage-selfhost-api-1  |     warnings: [Getter]
recipesage-selfhost-api-1  |   }
recipesage-selfhost-api-1  | }
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | Node.js v18.16.0
recipesage-selfhost-api-1  | Error while initializing firebase for notifications
recipesage-selfhost-api-1  | Database connection established
recipesage-selfhost-api-1  | Error while initializing firebase for notifications
recipesage-selfhost-api-1  | /app/node_modules/@elastic/transport/lib/Transport.js:528
recipesage-selfhost-api-1  |                             : new errors_1.ConnectionError(error.message, result);
recipesage-selfhost-api-1  |                               ^
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | ConnectionError: connect ECONNREFUSED 172.19.0.3:9200
recipesage-selfhost-api-1  |     at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)
recipesage-selfhost-api-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
recipesage-selfhost-api-1  |     at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)
recipesage-selfhost-api-1  |     at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {
recipesage-selfhost-api-1  |   meta: {
recipesage-selfhost-api-1  |     body: undefined,
recipesage-selfhost-api-1  |     statusCode: 0,
recipesage-selfhost-api-1  |     headers: {},
recipesage-selfhost-api-1  |     meta: {
recipesage-selfhost-api-1  |       context: null,
recipesage-selfhost-api-1  |       request: {
recipesage-selfhost-api-1  |         params: {
recipesage-selfhost-api-1  |           method: 'HEAD',
recipesage-selfhost-api-1  |           path: '/',
recipesage-selfhost-api-1  |           querystring: '',
recipesage-selfhost-api-1  |           headers: {
recipesage-selfhost-api-1  |             'user-agent': 'elastic-transport-js/8.3.1 (linux 5.15.0-1037-azure-x64; Node.js v18.16.0)',
recipesage-selfhost-api-1  |             'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',
recipesage-selfhost-api-1  |             accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         options: {},
recipesage-selfhost-api-1  |         id: 1
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       name: 'elasticsearch-js',
recipesage-selfhost-api-1  |       connection: Connection {
recipesage-selfhost-api-1  |         url: <ref *1> URL {
recipesage-selfhost-api-1  |           [Symbol(context)]: URLContext {
recipesage-selfhost-api-1  |             href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',
recipesage-selfhost-api-1  |             origin: 'http://elasticsearch:9200',
recipesage-selfhost-api-1  |             protocol: 'http:',
recipesage-selfhost-api-1  |             hostname: 'elasticsearch',
recipesage-selfhost-api-1  |             pathname: '/',
recipesage-selfhost-api-1  |             search: '',
recipesage-selfhost-api-1  |             username: 'elastic',
recipesage-selfhost-api-1  |             password: 'recipesage_selfhost',
recipesage-selfhost-api-1  |             port: '9200',
recipesage-selfhost-api-1  |             hash: ''
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(query)]: URLSearchParams {
recipesage-selfhost-api-1  |             [Symbol(query)]: [],
recipesage-selfhost-api-1  |             [Symbol(context)]: [Circular *1]
recipesage-selfhost-api-1  |           }
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         tls: null,
recipesage-selfhost-api-1  |         id: 'http://elasticsearch:9200/',
recipesage-selfhost-api-1  |         timeout: 30000,
recipesage-selfhost-api-1  |         headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },
recipesage-selfhost-api-1  |         deadCount: 0,
recipesage-selfhost-api-1  |         resurrectTimeout: 0,
recipesage-selfhost-api-1  |         _openRequests: 0,
recipesage-selfhost-api-1  |         weight: 1000,
recipesage-selfhost-api-1  |         pool: <ref *2> Pool {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false,
recipesage-selfhost-api-1  |           [Symbol(destroyed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onDestroyed)]: [],
recipesage-selfhost-api-1  |           [Symbol(closed)]: false,
recipesage-selfhost-api-1  |           [Symbol(onClosed)]: [],
recipesage-selfhost-api-1  |           [Symbol(queue)]: FixedQueue {
recipesage-selfhost-api-1  |             tail: [FixedCircularBuffer],
recipesage-selfhost-api-1  |             head: [FixedCircularBuffer]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(clients)]: [ [Client], [Client] ],
recipesage-selfhost-api-1  |           [Symbol(queued)]: 0,
recipesage-selfhost-api-1  |           [Symbol(onDrain)]: [Function: onDrain],
recipesage-selfhost-api-1  |           [Symbol(onConnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onDisconnect)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(onConnectionError)]: [Function (anonymous)],
recipesage-selfhost-api-1  |           [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },
recipesage-selfhost-api-1  |           [Symbol(dispatch interceptors)]: [],
recipesage-selfhost-api-1  |           [Symbol(connections)]: 256,
recipesage-selfhost-api-1  |           [Symbol(url)]: URL {
recipesage-selfhost-api-1  |             [Symbol(context)]: [URLContext],
recipesage-selfhost-api-1  |             [Symbol(query)]: [URLSearchParams]
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(options)]: {
recipesage-selfhost-api-1  |             keepAliveTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveMaxTimeout: 600000,
recipesage-selfhost-api-1  |             keepAliveTimeoutThreshold: 1000,
recipesage-selfhost-api-1  |             pipelining: 1,
recipesage-selfhost-api-1  |             maxHeaderSize: 16384,
recipesage-selfhost-api-1  |             headersTimeout: 30000,
recipesage-selfhost-api-1  |             bodyTimeout: 30000,
recipesage-selfhost-api-1  |             connect: [Function: connect],
recipesage-selfhost-api-1  |             interceptors: undefined
recipesage-selfhost-api-1  |           },
recipesage-selfhost-api-1  |           [Symbol(factory)]: [Function: defaultFactory],
recipesage-selfhost-api-1  |           [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],
recipesage-selfhost-api-1  |           [Symbol(needDrain)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(status)]: 'alive',
recipesage-selfhost-api-1  |         [Symbol(ca fingerprint)]: null,
recipesage-selfhost-api-1  |         [Symbol(diagnostics)]: Diagnostic {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         },
recipesage-selfhost-api-1  |         [Symbol(event emitter)]: EventEmitter {
recipesage-selfhost-api-1  |           _events: [Object: null prototype] {},
recipesage-selfhost-api-1  |           _eventsCount: 0,
recipesage-selfhost-api-1  |           _maxListeners: undefined,
recipesage-selfhost-api-1  |           [Symbol(kCapture)]: false
recipesage-selfhost-api-1  |         }
recipesage-selfhost-api-1  |       },
recipesage-selfhost-api-1  |       attempts: 3,
recipesage-selfhost-api-1  |       aborted: false
recipesage-selfhost-api-1  |     },
recipesage-selfhost-api-1  |     warnings: [Getter]
recipesage-selfhost-api-1  |   }
recipesage-selfhost-api-1  | }
recipesage-selfhost-api-1  |
recipesage-selfhost-api-1  | Node.js v18.16.0
recipesage-selfhost-api-1  | Error while initializing firebase for notifications
recipesage-selfhost-api-1  | Database connection established

```

**Comment by julianpoy** [comment]
Hey there @sandy9999 - missed that you had replied here.

Can you send the logs from the elasticsearch container? It looks like the API container cannot connect to the elasticsearch container.

**Comment by julianpoy** [comment]
Please pull the latest from this repository

**Comment by sandy9999** [comment]
Thank you @julianpoy . Pulling the latest from the repository helped solve the issue. I have another issue, but it's not related to this. I'll open a new one. Thanks again!
