### ISSUE TITLE
Cannot Exporting. get error

### ISSUE THREAD

**Issue by usernamenoweat** [julianpoy/RecipeSage-selfhost#53]
Error: ENOENT: no such file or directory, open '/api/images/filesystem/recipeImage/2023/7/1688744018914-70c409e41ed8f9'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getRecipeDataForExport (/app/packages/backend/src/routes/data.js:97:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/app/packages/backend/src/routes/data.js:142:23)

**Comment by julianpoy** [comment]
Hello! Sorry I missed this issue. Does the directory contain a file by that name, or did you change some config/update the RecipeSage container from minio?

**Comment by julianpoy** [comment]
Closing since no reply, but feel free to reopen!
