### ISSUE TITLE
Unable to register due to `recipesage_api_1` container error

### ISSUE THREAD

**Issue by Chaxiraxi** [julianpoy/RecipeSage-selfhost#55]
Hi,

I'm trying to set up a self-hosted instance of RecipeSage, but I'm encountering an error when I try to register. The `recipesage_api_1` container logs show this message:

```
POST /users/register?false=false& 500 199.842 ms - 1097
Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at <anonymous> (/app/node_modules/sequelize/lib/sequelize.js:315:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgresQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at Function.findAll (/app/node_modules/sequelize/lib/model.js:1140:21)
    at Function.findOne (/app/node_modules/sequelize/lib/model.js:1240:12)
    at <anonymous> (/app/packages/backend/src/routes/users.js:558:20)
    at <anonymous> (/app/node_modules/sequelize/lib/sequelize.js:507:18)
    at <anonymous> (/app/packages/backend/src/routes/users.js:545:19)
    at <anonymous> (/app/packages/backend/src/utils/wrapRequestWithErrorHandler.js:4:7)
```

I did not set the `DISABLE_REGISTRATION` env variable at all, and setting it to `false` dosen't help.

I have followed the instructions for running the migrations and have also tried to restart the containers. However, none of these steps solved the issue.

The other containers seem to be running fine, except for `recipesage_elasticsearch_1`, which I had to lower RAM requirements in `docker-compose.yml` by editing JVM arguments, but now it's running fine and is no longer bootlooping.

I also have an akward behaviour with `recipesage_api_1`  that bootloops like 3 times or so when I  `docker-compose up -d` with the following error:
```
Node.js v18.16.0
Error while initializing firebase for notifications
/app/node_modules/@elastic/transport/lib/Transport.js:528
                            : new errors_1.ConnectionError(error.message, result);
                              ^


ConnectionError: connect ECONNREFUSED 172.21.0.3:9200
    at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)
    at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {
  meta: {
    body: undefined,
    statusCode: 0,
    headers: {},
    meta: {
      context: null,
      request: {
        params: {
          method: 'HEAD',
          path: '/',
          querystring: '',
          headers: {
            'user-agent': 'elastic-transport-js/8.3.1 (linux 5.15.0-78-generic-x64; Node.js v18.16.0)',
            'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',
            accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'
          }
        },
        options: {},
        id: 1
      },
      name: 'elasticsearch-js',
      connection: Connection {
        url: <ref *1> URL {
          [Symbol(context)]: URLContext {
            href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',
            origin: 'http://elasticsearch:9200',
            protocol: 'http:',
            hostname: 'elasticsearch',
            pathname: '/',
            search: '',
            username: 'elastic',
            password: 'recipesage_selfhost',
            port: '9200',
            hash: ''
          },
          [Symbol(query)]: URLSearchParams {
            [Symbol(query)]: [],
            [Symbol(context)]: [Circular *1]
          }
        },
        tls: null,
        id: 'http://elasticsearch:9200/',
        timeout: 30000,
        headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },
        deadCount: 0,
        resurrectTimeout: 0,
        _openRequests: 0,
        weight: 1000,
        pool: <ref *2> Pool {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false,
          [Symbol(destroyed)]: false,
          [Symbol(onDestroyed)]: [],
          [Symbol(closed)]: false,
          [Symbol(onClosed)]: [],
          [Symbol(queue)]: FixedQueue {
            tail: [FixedCircularBuffer],
            head: [FixedCircularBuffer]
          },
          [Symbol(clients)]: [ [Client], [Client] ],
          [Symbol(queued)]: 0,
          [Symbol(onDrain)]: [Function: onDrain],
          [Symbol(onConnect)]: [Function (anonymous)],
          [Symbol(onDisconnect)]: [Function (anonymous)],
          [Symbol(onConnectionError)]: [Function (anonymous)],
          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },
          [Symbol(dispatch interceptors)]: [],
          [Symbol(connections)]: 256,
          [Symbol(url)]: URL {
            [Symbol(context)]: [URLContext],
            [Symbol(query)]: [URLSearchParams]
          },
          [Symbol(options)]: {
            keepAliveTimeout: 600000,
            keepAliveMaxTimeout: 600000,
            keepAliveTimeoutThreshold: 1000,
            pipelining: 1,
            maxHeaderSize: 16384,
            headersTimeout: 30000,
            bodyTimeout: 30000,
            connect: [Function: connect],
            interceptors: undefined
          },
          [Symbol(factory)]: [Function: defaultFactory],
          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],
          [Symbol(needDrain)]: false
        },
        [Symbol(status)]: 'alive',
        [Symbol(ca fingerprint)]: null,
        [Symbol(diagnostics)]: Diagnostic {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false
        },
        [Symbol(event emitter)]: EventEmitter {
          _events: [Object: null prototype] {},
          _eventsCount: 0,
          _maxListeners: undefined,
          [Symbol(kCapture)]: false
        }
      },
      attempts: 3,
      aborted: false
    },
    warnings: [Getter]
  }
}
```

I don't think this is related, but we never know.

**Comment by julianpoy** [comment]
This should be resolved in the latest release. Please re-clone the repo and setup again, and let me know if you still experience this issue.

ElasticSearch has been removed and replaced with Typesense, which is what RecipeSage is running in production these days.

**Comment by julianpoy** [comment]
Closing, but please re-open or create another issue if you have a problem.
