### ISSUE TITLE
Trying to Create an account but its throwing an error. 

### ISSUE THREAD

**Issue by msoffen** [julianpoy/RecipeSage-selfhost#67]
I'm using the Synologyinstall ( from https://mariushosting.com/how-to-install-recipesage-on-your-synology-nas/ ) and when I try to create a local account, Its giving an error.

"An unexpected error occurred. Please try again. If the problem continues to happen, please contact me." 

when I check the log via Portainer it has this error message in it 

POST /users/register?false=false& 500 3.975 ms - 945
Error: Registration is disabled
    at handler (/app/packages/backend/src/routes/users.js:626:13)
    at /app/packages/backend/src/utils/wrapRequestWithErrorHandler.js:4:13
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at cors (/app/node_modules/cors/lib/index.js:188:7)
    at /app/node_modules/cors/lib/index.js:224:17
    at originCallback (/app/node_modules/cors/lib/index.js:214:15)
    at /app/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/app/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/app/node_modules/cors/lib/index.js:204:7)

In the Stack setup, I do have this set to false 
      DISABLE_REGISTRATION: false

I'm running the 2.12.7 version **[julianpoy/recipesage-selfhost:api-v2.12.7]**

I'm new to the portainer/etc. stuff so please bear with me.

Is there any other settings that would be responsible for not allowing me to create an account?

Is there any way to create the account via the CLI ?

**Comment by Cavekeeper** [comment]
I can confirm the issue with "julianpoy/recipesage-selfhost:static-v2.12.10".
After the reinstallation I was able to create an account.
Then I prevented the registration with “DISABLE_REGISTRATION: true”. That worked.
Now I wanted to add a new account and inserted "DISABLE_REGISTRATION: false" again.
No new registrations can now take place either.
I also found this LOG:

POST /users/register?false=false& 500 25.900 ms - 945
Error: Registration is disabled
at handler (/app/packages/backend/src/routes/users.js:626:13)
at /app/packages/backend/src/utils/wrapRequestWithErrorHandler.js:4:13
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/express/lib/router/route.js:144:13)
at cors (/app/node_modules/cors/lib/index.js:188:7)
at /app/node_modules/cors/lib/index.js:224:17
at originCallback (/app/node_modules/cors/lib/index.js:214:15)
at /app/node_modules/cors/lib/index.js:219:13
at optionsCallback (/app/node_modules/cors/lib/index.js:199:9)
at corsMiddleware (/app/node_modules/cors/lib/index.js:204:7)

At the moment I haven't found a solution for this either.

**Comment by julianpoy** [comment]
Currently at work so can't give a detailed reply, but please remove the environment variable completely rather than setting its value to false.

**Comment by Cavekeeper** [comment]
> Currently at work so can't give a detailed reply, but please **remove the environment variable completely** rather than setting its value to false.

@julianpoy Thank you very much, that solved the problem regarding my matter.

**Comment by msoffen** [comment]
BINGO !

That worked.
